server:
  port: 8084

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/movie_ticket_db
    username: root
    password: Krushangi1979@@

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

eureka:
  client:
    enabled: false